//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultStatus", Namespace="Camstar.Security.RBAC.Interfaces")]
    public partial class ResultStatus : object
    {
        
        private ServiceReference1.ExceptionDataType ExceptionDataField;
        
        private bool IsSuccessField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExceptionDataType ExceptionData
        {
            get
            {
                return this.ExceptionDataField;
            }
            set
            {
                this.ExceptionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionDataType", Namespace="Camstar.Security.RBAC.Interfaces")]
    public partial class ExceptionDataType : object
    {
        
        private int CodeField;
        
        private string DescriptionField;
        
        private ServiceReference1.ExceptionLevel ExceptionLevelField;
        
        private string SourceField;
        
        private string failureContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExceptionLevel ExceptionLevel
        {
            get
            {
                return this.ExceptionLevelField;
            }
            set
            {
                this.ExceptionLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string failureContext
        {
            get
            {
                return this.failureContextField;
            }
            set
            {
                this.failureContextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionLevel", Namespace="Camstar.Security.RBAC.Interfaces")]
    public enum ExceptionLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Service = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Server = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAuthenticationService")]
    public interface IAuthenticationService
    {
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Login", ReplyAction="http://tempuri.org/IAuthenticationService/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.LoginResponse> LoginAsync(ServiceReference1.LoginRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginFromXMLClient", ReplyAction="http://tempuri.org/IAuthenticationService/LoginFromXMLClientResponse")]
        System.Threading.Tasks.Task<ServiceReference1.LoginFromXMLClientResponse> LoginFromXMLClientAsync(ServiceReference1.LoginFromXMLClientRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginFromClient", ReplyAction="http://tempuri.org/IAuthenticationService/LoginFromClientResponse")]
        System.Threading.Tasks.Task<ServiceReference1.LoginFromClientResponse> LoginFromClientAsync(ServiceReference1.LoginFromClientRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginWithPasswordExpiration", ReplyAction="http://tempuri.org/IAuthenticationService/LoginWithPasswordExpirationResponse")]
        System.Threading.Tasks.Task<ServiceReference1.LoginWithPasswordExpirationResponse> LoginWithPasswordExpirationAsync(ServiceReference1.LoginWithPasswordExpirationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Logout", ReplyAction="http://tempuri.org/IAuthenticationService/LogoutResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultStatus> LogoutAsync(string sessionGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/ValidateSession", ReplyAction="http://tempuri.org/IAuthenticationService/ValidateSessionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultStatus> ValidateSessionAsync(string sessionGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/AuthenticateImpersonator", ReplyAction="http://tempuri.org/IAuthenticationService/AuthenticateImpersonatorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultStatus> AuthenticateImpersonatorAsync(string loggedInSessionGuid, string loggedInUserName, string userDomain, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/ReAuthenticatePassword", ReplyAction="http://tempuri.org/IAuthenticationService/ReAuthenticatePasswordResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultStatus> ReAuthenticatePasswordAsync(string sessionGuid, string userName, string password);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userDomain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sessionGuid;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(string userDomain, string userName, string password, string sessionGuid)
        {
            this.userDomain = userDomain;
            this.userName = userName;
            this.password = password;
            this.sessionGuid = sessionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ResultStatus LoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sessionGuid;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(ServiceReference1.ResultStatus LoginResult, string sessionGuid)
        {
            this.LoginResult = LoginResult;
            this.sessionGuid = sessionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginFromXMLClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginFromXMLClientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sessionGuid;
        
        public LoginFromXMLClientRequest()
        {
        }
        
        public LoginFromXMLClientRequest(string userName, string password, string sessionGuid)
        {
            this.userName = userName;
            this.password = password;
            this.sessionGuid = sessionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginFromXMLClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginFromXMLClientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ResultStatus LoginFromXMLClientResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sessionGuid;
        
        public LoginFromXMLClientResponse()
        {
        }
        
        public LoginFromXMLClientResponse(ServiceReference1.ResultStatus LoginFromXMLClientResult, string sessionGuid)
        {
            this.LoginFromXMLClientResult = LoginFromXMLClientResult;
            this.sessionGuid = sessionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginFromClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginFromClientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userDomain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string appName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sessionGuid;
        
        public LoginFromClientRequest()
        {
        }
        
        public LoginFromClientRequest(string userDomain, string userName, string password, string appName, string sessionGuid)
        {
            this.userDomain = userDomain;
            this.userName = userName;
            this.password = password;
            this.appName = appName;
            this.sessionGuid = sessionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginFromClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginFromClientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ResultStatus LoginFromClientResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sessionGuid;
        
        public LoginFromClientResponse()
        {
        }
        
        public LoginFromClientResponse(ServiceReference1.ResultStatus LoginFromClientResult, string sessionGuid)
        {
            this.LoginFromClientResult = LoginFromClientResult;
            this.sessionGuid = sessionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWithPasswordExpiration", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginWithPasswordExpirationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userDomain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string appName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sessionGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int PasswordDaysRemaining;
        
        public LoginWithPasswordExpirationRequest()
        {
        }
        
        public LoginWithPasswordExpirationRequest(string userDomain, string userName, string password, string appName, string sessionGuid, int PasswordDaysRemaining)
        {
            this.userDomain = userDomain;
            this.userName = userName;
            this.password = password;
            this.appName = appName;
            this.sessionGuid = sessionGuid;
            this.PasswordDaysRemaining = PasswordDaysRemaining;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWithPasswordExpirationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginWithPasswordExpirationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ResultStatus LoginWithPasswordExpirationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sessionGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int PasswordDaysRemaining;
        
        public LoginWithPasswordExpirationResponse()
        {
        }
        
        public LoginWithPasswordExpirationResponse(ServiceReference1.ResultStatus LoginWithPasswordExpirationResult, string sessionGuid, int PasswordDaysRemaining)
        {
            this.LoginWithPasswordExpirationResult = LoginWithPasswordExpirationResult;
            this.sessionGuid = sessionGuid;
            this.PasswordDaysRemaining = PasswordDaysRemaining;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAuthenticationServiceChannel : ServiceReference1.IAuthenticationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IAuthenticationService>, ServiceReference1.IAuthenticationService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationServiceClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LoginResponse> LoginAsync(ServiceReference1.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LoginFromXMLClientResponse> LoginFromXMLClientAsync(ServiceReference1.LoginFromXMLClientRequest request)
        {
            return base.Channel.LoginFromXMLClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LoginFromClientResponse> LoginFromClientAsync(ServiceReference1.LoginFromClientRequest request)
        {
            return base.Channel.LoginFromClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LoginWithPasswordExpirationResponse> LoginWithPasswordExpirationAsync(ServiceReference1.LoginWithPasswordExpirationRequest request)
        {
            return base.Channel.LoginWithPasswordExpirationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultStatus> LogoutAsync(string sessionGuid)
        {
            return base.Channel.LogoutAsync(sessionGuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultStatus> ValidateSessionAsync(string sessionGuid)
        {
            return base.Channel.ValidateSessionAsync(sessionGuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultStatus> AuthenticateImpersonatorAsync(string loggedInSessionGuid, string loggedInUserName, string userDomain, string userName, string password)
        {
            return base.Channel.AuthenticateImpersonatorAsync(loggedInSessionGuid, loggedInUserName, userDomain, userName, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultStatus> ReAuthenticatePasswordAsync(string sessionGuid, string userName, string password)
        {
            return base.Channel.ReAuthenticatePasswordAsync(sessionGuid, userName, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthenticationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthenticationService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthenticationService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost/CamstarSecurityServices/AuthenticationService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthenticationService1))
            {
                return new System.ServiceModel.EndpointAddress("http://win-61rcg6tf13s/CamstarSecurityServices/AuthenticationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuthenticationService,
            
            BasicHttpBinding_IAuthenticationService1,
        }
    }
}
